---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен видеть на странице товара и в каталоге название товара, рейтинг товара, цену со скидкой и без
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавлении товара в корзину
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть SPA приложением, которое не перезагружает страницу
implicit:
  - При смене языка сайта с английского на русский (и наоборот) должна автоматически изменяться валюта и отображаемая цена (для английской версии — доллар, для русской — рубль)
  - Числа в фильтре 'цена' должны быть неотрицательными
  - Результаты поиска по ключевому слову или категории должны включать только товары, у которых название начинается с введенного ключевого слова или полностью совпадает с ним
  - Выбранный язык интерфейса должен сохранятся при обновлении страницы
  - Кнопка 'В корзину' должна быть синего цвета (#0d6efd)
